import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { LuDownload, LuArrowRight, LuCircleAlert } from 'react-icons/lu';
import AnswerComparison from './AnswerComparison';
import axiosInstance from '../../../utils/axiosInstance';
import { API_PATHS } from '../../../utils/apiPaths';
import './ReportGenerator.css';

const ReportGenerator = ({ questions, userAnswers, sessionData, onExit }) => {
  const [reviewingQuestionIndex, setReviewingQuestionIndex] = useState(null);
  const [aiReport, setAiReport] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState('');

  const totalQuestions = questions.length;
  const answeredQuestions = Object.keys(userAnswers).length;
  const completionRate = (answeredQuestions / totalQuestions) * 100;

  // Calculate performance score (basic: answered questions)
  const performanceScore = answeredQuestions > 0 ? Math.round(completionRate) : 0;

  useEffect(() => {
    const fetchReport = async () => {
      try {
        setAiLoading(true);
        setAiError('');
        const payload = {
          questions: questions.map((q) => ({
            question: q.question,
            // use any available answer shape
            answer: q.answer || q.expected_answer || q.expectedAnswer || "",
          })),
          userAnswers,
          role: sessionData?.role,
          experience: sessionData?.experience,
          topicsToFocus: sessionData?.topicsToFocus,
        };
        const res = await axiosInstance.post(API_PATHS.AI.GENERATE_REPORT, payload);
        setAiReport(res.data);
      } catch (err) {
        setAiError('Could not fetch AI report.');
      } finally {
        setAiLoading(false);
      }
    };

    if (questions?.length) {
      fetchReport();
    }
  }, [questions, userAnswers, sessionData]);

  // Generate PDF report
  const generatePDFReport = () => {
    const reportContent = questions
      .map((q, idx) => {
        const userAnswer = userAnswers[idx] || 'Not answered';
        return `
Question ${idx + 1}: ${q.question}

Your Answer:
${userAnswer}

Expected Answer:
${q.answer}

---
`;
      })
      .join('\n');

    const report = `
INTERVIEW SIMULATION REPORT
==========================
Date: ${new Date().toLocaleString()}
Session: ${sessionData?.role} - ${sessionData?.experience} years experience
Topics: ${sessionData?.topicsToFocus}

SUMMARY
-------
Total Questions: ${totalQuestions}
Questions Answered: ${answeredQuestions}
Completion Rate: ${completionRate.toFixed(1)}%
Performance Score: ${performanceScore}%

DETAILED ANSWERS
----------------
${reportContent}

---
Generated by Interview Prep AI
`;

    // Create blob and download
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `interview-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="report-generator">
      {reviewingQuestionIndex !== null ? (
        <div className="review-mode">
          <button
            className="back-to-report-btn"
            onClick={() => setReviewingQuestionIndex(null)}
          >
            ← Back to Report
          </button>
          <AnswerComparison
            question={questions[reviewingQuestionIndex].question}
            userAnswer={userAnswers[reviewingQuestionIndex] || 'Not answered'}
            aiAnswer={questions[reviewingQuestionIndex].answer}
            feedback={{ isComplete: !!userAnswers[reviewingQuestionIndex] }}
          />
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="report-content"
        >
          {/* Report Header */}
          <div className="report-header">
            <h2>Interview Simulation Complete!</h2>
            <p className="report-subtitle">Review your performance below</p>
          </div>

          {/* Performance Summary */}
          <div className="performance-summary">
            <div className="summary-card score-card">
              <div className="score-circle">
                <span className="score-number">{performanceScore}%</span>
                <span className="score-label">Completion</span>
              </div>
              <p className="score-description">
                You answered {answeredQuestions} out of {totalQuestions} questions
              </p>
            </div>

            <div className="summary-card stats-card">
              <div className="stat-item">
                <span className="stat-icon">
                  ✅
                </span>
                <span className="stat-label">Questions Answered</span>
                <span className="stat-value">{answeredQuestions}/{totalQuestions}</span>
              </div>
              <div className="stat-item">
                <span className="stat-icon">
                  <LuCircleAlert />
                </span>
                <span className="stat-label">Skipped</span>
                <span className="stat-value">{totalQuestions - answeredQuestions}</span>
              </div>
            </div>

            <div className="summary-card session-info">
              <p className="info-label">Session Info</p>
              <div className="info-content">
                <div className="info-item">
                  <span className="info-key">Role:</span>
                  <span className="info-val">{sessionData?.role}</span>
                </div>
                <div className="info-item">
                  <span className="info-key">Experience:</span>
                  <span className="info-val">{sessionData?.experience} years</span>
                </div>
                <div className="info-item">
                  <span className="info-key">Date:</span>
                  <span className="info-val">{new Date().toLocaleDateString()}</span>
                </div>
              </div>
            </div>
          </div>

          <div className="summary-card ai-report mb-6">
              <p className="info-label">AI Coach Report</p>
              {aiLoading && <p className="text-sm text-gray-600">Generating report...</p>}
              {aiError && <p className="text-sm text-amber-700">{aiError}</p>}
              {!aiLoading && aiReport && (
                <div className="ai-report-body">
                  <p className="text-sm text-gray-800 font-semibold">Summary</p>
                  <p className="text-sm text-gray-700 mb-2">{aiReport.summary}</p>
                  {aiReport.strengths?.length > 0 && (
                    <div className="text-sm text-emerald-800 mb-2">
                      <p className="font-semibold">Strengths</p>
                      <ul className="list-disc ml-4">
                        {aiReport.strengths.map((s, idx) => (
                          <li key={idx}>{s}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {aiReport.improvements?.length > 0 && (
                    <div className="text-sm text-amber-800 ">
                      <p className="font-semibold">Improvements</p>
                      <ul className="list-disc ml-4">
                        {aiReport.improvements.map((s, idx) => (
                          <li key={idx}>{s}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>

          {/* Questions Overview */}
          <div className="questions-overview">
            <h3>Questions Overview</h3>
            {aiReport?.perQuestion?.length > 0 && (
              <div className="ai-per-question">
                <h4>AI Feedback</h4>
                <ul className="ai-per-question-list">
                  {aiReport.perQuestion.map((item, idx) => (
                    <li key={idx} className="ai-per-question-item">
                      <div className="ai-pq-header">
                        <span className="q-number">{idx + 1}</span>
                        <span className="q-status capitalize">{item.verdict}</span>
                      </div>
                      <p className="q-text">{item.question}</p>
                      <p className="q-feedback">{item.feedback}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            <div className="questions-list mt-6 border-blue-200 border-4 p-4">
              <p className='text-blue-600 text-lg font-semibold'>Questions List, Given Answers and Expected Answers</p>
              {questions.map((question, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className={`question-item ${userAnswers[index] ? 'answered' : 'skipped'}`}
                >
                  <span className="q-number">{index + 1}</span>
                  <div className="q-info">
                    <p className="q-text">{question.question}</p>
                    <span className={`q-status ${userAnswers[index] ? 'answered' : 'skipped'}`}>
                      {userAnswers[index] ? 'Answered' : 'Skipped'}
                    </span>
                  </div>
                  <button
                    className="review-btn"
                    onClick={() => setReviewingQuestionIndex(index)}
                  >
                    Review <LuArrowRight size={16} />
                  </button>
                </motion.div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="report-actions">
            <button className="action-btn text-blue-600" onClick={generatePDFReport}>
              <LuDownload /> Download Report
            </button>
            <button className="action-btn text-blue-600" onClick={onExit}>
              Exit & Back to Dashboard
            </button>
          </div>

          {/* Recommendations */}
          <div className="recommendations">
            <h3>Recommendations</h3>
            <ul className="recommendations-list">
              <li>Review the answers you skipped and try to answer them</li>
              <li>Compare your answers with the AI expected answers</li>
              <li>Focus on areas where your answer differs from the expected answer</li>
              <li>Practice more questions in weak topic areas</li>
              <li>Take the interview simulation again to track progress</li>
            </ul>
          </div>
        </motion.div>
      )}
    </div>
  );
};

export default ReportGenerator;
